version: '2'
services:
  mariadb:
    image: "mariadb:10.10.2"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: random
      MYSQL_DATABASE: idealvoting
      MYSQL_USER: idealvoting
      MYSQL_PASSWORD: idealvoting
  mailhog:
    image: "mailhog/mailhog:v1.0.1"
